name: Build LoopFollow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Install Bundler and dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run pod install (via Bundler)
        run: bundle exec pod install

      - name: Build with Fastlane
        run: bundle exec fastlane build_LoopFollow